# local node nodeID
local = "node_1"
# leader node nodeID
leader = "node_1"
# local node role "leader" or "generator"
role = "leader"
# local bls private key for bls signature
privKey = "="
# the threshold number of collected signatures for aggregating
blsThreshold = 2
# the length of chan which is used to buffer and store requests to generate random numbers from the client to the leader.
rpcChanLen = 10
# grpc port for server which handle internal message sending among nodes
grpcServerPort = "0.0.0.0:9001"
# Retry 'connMaxAttempts' times for creating grpc connection, delay 'retryDelay' between two attempts
connMaxAttempts = 3
# delay time duration between two grpc connection attempts
retryDelay = "1s"
#retryUnconnectedNodeDuration = "3s"
# for a "generate random number" request, there is a timeout period, and the timeout request will be rejected at any stage.
timeoutDuration = "2s"
# the time between the start of a discard and the end of the last discard
discardDuration = "10s"
# if leader is restarted with running generators, the seq is backward and db record not worked, could set lastDiscardSeq to a bigger num(>= seq in generator)
lastDiscardSeq = -1
# randomNumbersPool stores random numbers can be returned to client,
# if the calculated data with pool size exceeds this limit, new random numbers will no longer be generated.
randomNumbersPoolUpperLimit = 20  # only leader need

# Log Level
logLevel = "debug"

# Web Server
apiServiceAddress = ":8080"

# SDK
enableSDK = true
exposedRpcAddress = ":8081"

[ethConfig]
must = false
chainUrl = "http://127.0.0.1:8545"
chainID = 31337
contractAddress = "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1"
privKey = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# nodeInfos is the config list of remote nodes
[[nodeInfos]]
nodeID = "node_2"
url = "localhost:9002"
pubKey = "YBOQS5J342N9BwCWcvtme7v+xLE66PIBOYBsHJpom8PldLqFa7GoIWbaHBzQIXwl/Rc8hp5sz4DHx0A4tlDrTeyhP1AxC2jxLtxdcQAcJuElM096wUi3SHRlBkWHeLe0GxbClkVLAHFw3w2igcfFtjF8SVG0sAk3obur/4ogWFC/oVV0GTTeS4L/edNrBObIBgHGeE5PDOXTnQrStGV9vi3rbLEfECJk8W+A4HsWpCjwV7Xinm7VlS0yJUElA/rvkBY7KwIA2yvclH9xYcAlfGhbLwReESdaeLq58jVqQiuIQzlyZ8xbUyO1NfQtAb/sUAMgfCp/ARlqVNWsEBP/7IlPIDGJnoLhkIqryFdIJ05lDfY1J+pZB7xWjh0+/qE3FQ=="

[[nodeInfos]]
nodeID = "node_3"
url = "localhost:9003"
pubKey = "YAEDyEIIv0vmDrfkALVk0jKM1GVXJql8Es29zUBcN6B4Je/zhC8oN9tRRCODU8dn/BiJs7sq2HH/ABUuV27dLaCj//Ub4HSil1pGk/08VzmWcoyZN0FL0UqQNmTvMyl1YhNhbQQs+9Aa447AoO7O4LN8ioRU/wmq75myvcTlwW6taD+Tg7gQswglbnjgCYQGbhm3O1T0e+uxnIZlMTyQXKAN69A5mLv3JFgXR6CwTI9Yoz7O83m7NOBRXeXMKlkGFAmqLI9gpxYa6Dhz3qBkcwJhdUakR7uBfrHwew8ghQvKU5fno9xN1rR5inKHlQ/kKws73soP02AXQaUyD5bTeR/kUpwJ3RsE5hoEUuZpha0PLNq7YIj8PYjHlaBiZD5hfw=="