local = "local"
leader = "leader"
role = "generator"
privKey = ""
blsThreshold = 3
rpcChanLen = 10
grpcServerPort = "9001"
connMaxAttempts = 3
retryDelay = "1s"
#retryUnconnectedNodeDuration = "3s"
timeoutDuration = "3s"
discardDuration = "1s"
lastDiscardSeq = -1
randomNumbersPoolUpperLimit = 10  # only leader need

# log level
logLevel = ""

# web server
apiServiceAddress = ":8080"

# sdk
enableSDK = true
exposedRpcAddress = ""

[ethConfig]
chainUrl = ""
chainID = ""
contractAddress = ""
privKey = ""

[[nodeInfos]]
nodeID = "node_1"
url = "localhost:1001"
pubKey = ""
[[nodeInfos]]
nodeID = "node_2"
url = "localhost:1002"
pubKey = ""